server:
  port: 2525
  servlet:
    context-path: /atps
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: jeebankishore95@gmail.com
    password: jinujinu
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  datasource:
    url: jdbc:mysql://localhost:3306/atps_project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    

passwordlength: 8
mailSent: The temporary password has been sent to your email, Kindly unlock your account to access our services